MODEL:
  BERT_CKPT: "output/macbert4csc"
  DEVICE: "cuda"
  NAME: "macbert4csc"
  GPU_IDS: [0]
  # [loss_coefficient]
  HYPER_PARAMS: [0.2]
  WEIGHTS: "output/macbert4csc/epoch=03-val_loss=0.02.ckpt"
  #WEIGHTS: ""
DATASETS:
  TRAIN: "output/train.json"
  VALID: "output/preliminary_val_spell.json"
  TEST: "output/preliminary_val_spell.json"

SOLVER:
  BASE_LR: 5e-5
  WEIGHT_DECAY: 0.01
  BATCH_SIZE: 16
  MAX_EPOCHS: 4
  ACCUMULATE_GRAD_BATCHES: 4

OUTPUT_DIR: "output/macbert4csc"
MODE: ["train", "test"]
