cd .. && CUDA_VISIBLE_DEVICES=0,1,2,3 python -m src.train \
--in_model_dir "/workspace/syntactic-experts/model/model_MiduCTC/model/ctc_2022Y07M27D23H/epoch1,step180,testf1_44_9%,devf1_44_9%" \
--out_model_dir "../model/ctc" \
--epochs "50" \
--batch_size "32" \
--max_seq_len "384" \
--learning_rate "5e-5" \
--train_fp "/workspace/syntactic-experts/model/model_MiduCTC/data/preliminary_a_data/preliminary_train.json" \
--dev_fp "/workspace/syntactic-experts/model/model_MiduCTC/data/preliminary_a_data/preliminary_val.json" \
--test_fp "/workspace/syntactic-experts/model/model_MiduCTC/data/preliminary_a_data/preliminary_val.json" \
--random_seed_num "22" \
--check_val_every_n_epoch "1" \
--early_stop_times "20" \
--warmup_steps "-1" \
--dev_data_ratio "0.1" \
--training_mode "normal" \
--amp true \
--freeze_embedding false