MODEL:
  BERT_CKPT: "pretrained/macbert4csc"
  DEVICE: "cuda"
  NAME: "macbert4csc"
  GPU_IDS: [0]
  # [loss_coefficient]
  HYPER_PARAMS: [0.2]
  WEIGHTS: "pretrained/macbert4csc/epoch=02-val_loss=0.02.ckpt"
  #WEIGHTS: ""
DATASETS:
  TRAIN: "output/preliminary_train_words_spell_confusion2.json"
  VALID: "output/final_val.json"
  TEST: "output/preliminary_val.json"

SOLVER:
  BASE_LR: 5e-5
  WEIGHT_DECAY: 0.01
  BATCH_SIZE: 16
  MAX_EPOCHS: 2
  ACCUMULATE_GRAD_BATCHES: 4

OUTPUT_DIR: "output/macbert4csc"
MODE: ["train", "test"]
